---
name: Gatherer Bug
description: Submit a Gatherer bug
labels: ["gatherer"]
body:
- type: markdown
  attributes:
    value: |
      This form is for reporting errors seen on [Gatherer](https://gatherer.wizards.com/), the online Oracle card reference for *Magic: the Gathering*.

      Gatherer is now over 20 years old and experiences significant growing pains keeping up with the game's current state. Small errors are expected from time to time.
      You can help us keep track of them here so they're available for reference and to help us raise them to the attention of Wizards of the Coast.

      If you have issues or questions about Scryfall itself or its API, you instead want [our contact form](https://scryfall.com/contact).
- type: textarea
  id: problem
  attributes:
    label: Describe the problem
    description: "Include screenshots and directions to the problematic page(s) if applicable"
    placeholder: |
      On the page for Hunted Wumpus, there's a problem with ...
      
      See here: https://gatherer.wizards.com/Pages/...
  validations:
    required: true
- type: input
  id: reference
  attributes:
    label: WotC report reference (optional)
    description: If you reported this to WotC already and received a report link or reference number, please include it here.
---
